{% set name = "tsinfer" %}
{% set version = "0.4.1" %}
{% set sha256 = "4902bc6bd4692a374e5e98178044279048f76b43e793d05cc17087f56bc14dc0" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tsinfer-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - tsinfer=tsinfer.__main__:main
  skip: true  # [py<39]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    # Support for osx_arm64 as per
    # https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - numpy
    - pip
    - python
    - setuptools
    - setuptools-scm
  run:
    - attrs >=19.2.0
    - daiquiri
    - humanize
    - python-lmdb
    - numcodecs >=0.6
    - numba
    - psutil
    - python
    - sortedcontainers
    - tqdm
    - tskit >=0.5.3
    - zarr >=2.2,!=2.11.0,!=2.11.1,!=2.11.2,<3

test:
  imports:
    - tsinfer
  commands:
    - tsinfer --help

about:
  home: https://github.com/tskit-dev/tsinfer
  summary: Infer tree sequences
  description: |
    tsinfer infers succinct tree sequences from observed genetic variation data
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://tskit.dev/tsinfer/docs
  dev_url: https://github.com/tskit-dev/tsinfer

extra:
  recipe-maintainers:
    - benjeffery
    - jeromekelleher
    - petrelharp
