{% set name = "tsinfer" %}
{% set version = "0.2.3" %}
{% set sha256 = "4627f033467920d0fae733e9fe10862320ede5176194135a2ff88bae4e44dd42" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tsinfer-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - tsinfer=tsinfer.__main__:main
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
    - setuptools-scm
  run:
    - attrs >=19.2.0
    - daiquiri
    - humanize
    - python-lmdb
    - numcodecs >=0.6
    - python
    - six
    - sortedcontainers
    - tqdm
    - tskit >=0.3.3
    - zarr >=2.2,!=2.11.0,!=2.11.1,!=2.11.2
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - tsinfer
  commands:
    - tsinfer --help

about:
  home: https://github.com/tskit-dev/tsinfer
  summary: Infer tree sequences
  description: |
    tsinfer infers succinct tree sequences from observed genetic variation data
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://tskit.dev/tsinfer/docs
  dev_url: https://github.com/tskit-dev/tsinfer

extra:
  recipe-maintainers:
    - benjeffery
    - jeromekelleher
